theme: jekyll-theme-minimal
title: Jinrui Gou
logo: /profile.jpg



keywords: Homepage, CV, Academic, Graph Neural Nets
description: Homepage


author:
    name: Jinrui Gou
    email: jg6226@nyu.edu  
    github: linmengsysu  
    linkedin: Jinrui (Jerry) Gou

avatar: /profile.jpg

