theme: jekyll-theme-minimal
title: Lin Meng | 孟琳
logo: /profile.jpg



keywords: Homepage, CV, Academic, Graph Neural Nets
description: Homepage


author:
    name: Lin Meng
    email: lin@ifmlab.org  
    github: linmengsysu  
    linkedin: Lin Meng 

avatar: /profile.jpg

